---
title: Evan O'Grady
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: /projects/:title/
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
email: e + LAST NAME + 617 AT gmail DOT com
description: Evan O'Grady's webpage, projects, biography, resume, and FAQ
baseurl: ''
url: //eogrady617.github.io
urls:
- text: Home
  url: "/"
  display: true
- text: Projects
  url: "/projects/"
  display: true
- text: Résumé
  url: "/resume/"
  display: true
- text: Coursework
  url: "/coursework/"
  display: true
- text: Feedback
  url: "/feedback/"
  display: true
author_logo: profile.png
author: Evan O'Grady
author_bio: Hi! I'm currently a Master's student in Quantum Science and Technology at UCLA, 
  with a background in Computer Engineering. My main interests are optics/photonics, quantum
  networks, quantum computer science, and quantum hardware engineering. I am skilled in scientific
  computing and hands-on optics experiments.
author_bio2: I love science and engineering and I'm always looking to learn more about how things work 
  and how we can improve them. I also enjoy teaching and mentoring others because I find it to be rewarding 
  and a great way to strengthen my own understanding of concepts. My current career goal is to secure a full-time 
  position in a quantum science related role. Eventually, I'd like to pursue a Ph.D. 
author_bio3: ''
author_location: Los Angeles, CA
author_website_url: eogrady617.github.io
author_work_experiences:
- company_name: The Aerospace Corporation
  company_logo: aero.png
  dates: Incoming June 2026
  designation: Photonic Technologies Intern
  description:
  - ''
  visibility: true
- company_name: National Science Foundation
  company_logo: nsf.png
  dates: May 2024 - May 2025
  designation: Undergraduate Researcher (IRES Program, Advisor Dr. Yi Wang)
  description:
  - Selected as one of 6 undergrads for the NSF's International Research Experience for Students (IRES) program in Zaragoza, Spain
  - Investigated newest innovations in large language models, object detection, and speech recognition machine learning
  - Developed an AI-based assistant for the visually impaired using Python
  - Collaborated with professors and students from the University of Zaragoza, Manhattan University, and City University of New York
  - Presented results at IEEE SoutheastCon 2025
  visibility: true
author_education_details:
- college_logo: ucla.png
  college_name: University of California, Los Angeles
  college_degree: Master's in Quantum Science and Technology
  description:
  visibility: true
- college_logo: mu.png
  college_name: Manhattan University
  dates: 2021 - 2025
  college_degree: B.S. in Computer Engineering
  description: Magna Cum Laude, HKN Honors Society, Annual Presidential Scholarship, Epsilon Sigma Pi Honors, Dean''s List.
  visibility: true
author_other_experiences:
- company_name: Nova Scholar Education
  company_logo: novascholar.png
  dates: July 2025 - Present
  designation: Research Mentor
  description:
  - Guide high school students through the process of completing a research project
  - Provide subject matter expertise to students interested in research related to engineering and computer science
  - Introduce students to the principles and practice of academic research
  visibility: true
- company_name: Stanford University's Code in Place
  company_logo: cip.png
  dates: Summer 2025
  designation: Section Leader
  description:
  - Taught fundamentals of Python programming through one of the largest free computer science education initiatives in the world
  - Successfully led a group of ~15 diverse students through the first half of Stanford's intro to Python course
  - Gained interpersonal skills, practiced engaging pedagogy, and demonstrated mastery of Python principles
  visibility: true
- company_name: IEEE HKN Honors Society
  company_logo: hkn.png
  dates: August 2024 - May 2025
  designation: Tutor/Mentor
  description:
  - Held weekly open tutoring hours for peer students in select math and electrical engineering courses
  - Mentored two underclassmen in professional and academic advice
  visibility: true
author_skills:
  technical:
  - Quantum and Classical Optics
  - Scientific Computing
  - Quantum Networking
  - RF Electronics
  - Quantum Algorithms
  - Neural Networks
  - Scientific Writing
  
  instrumentation:
  - Lasers
  - Optomechanics
  - Optical Fibers
  - Single-Photon Detectors (gmAPDs, SNSPDs)
  - Acousto-Optic Modulators
  - RFSoC Boards
  - Test Equipment (Oscilloscopes, Spectrum Analyzers)

  software:
  - Python
  - Unix Shell
  - C / C++
  - PyTorch
  - Qiskit
  - PennyLane

accomplishments:
- Add your accomplishments and milestones here
#github_username: eogrady617
linkedin_username: evanjogrady
orcid_id: 0009-0007-1713-5664
formspree_email: eogrady617@gmail.com
new_formspring_endpoint: mkoyazwr
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: ''
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
plugins:
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-algolia
- jekyll-redirect-from
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - development
