---
title: Evan O'Grady
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: /projects/:title/
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
email: e + LAST NAME + 617 AT gmail DOT com
description: Evan O'Grady's webpage, projects, biography, resume, and FAQ
baseurl: ''
url: //eogrady617.github.io
urls:
- text: Home
  url: "/"
  display: true
- text: Projects
  url: "/projects/"
  display: true
- text: Resume
  url: "/resume/"
  display: true
- text: Coursework
  url: "/coursework/"
  display: true
- text: Feedback
  url: "/feedback/"
  display: true
author_logo: profile.png
author: Evan O'Grady
author_bio: Hi! I'm currently a Master's student in Quantum Science and Technology at UCLA, 
  with a background in Computer Engineering. My main interests are optics/photonics, quantum
  networks, quantum programming, and quantum hardware engineering. I am skilled in scientific 
  computing and experimental optics.
author_bio2: My career goals are to work in an industry role related to quantum science 
  and eventually pursue a PhD.
author_bio3: ''
author_location: Los Angeles, CA
author_website_url: eogrady617.github.io
author_work_experiences:
- company_name: The Aerospace Corporation
  company_logo: aero.png
  dates: Incoming June 2026
  designation: Photonic Technologies Intern
  description:
  - Add your key accomplishments and responsibilities here
  visibility: true
author_education_details:
- college_logo: ucla.png
  college_name: University of California, Los Angeles
  college_degree: Master's in Quantum Science and Technology
  description: Add details about your education, focus areas, and achievements.
  visibility: true
- college_logo: mu.png
  college_name: Manhattan University
  dates: 2021 - 2025
  college_degree: B.S. in Computer Engineering
  description: Add details about your education, focus areas, and achievements.
  visibility: true
accomplishments:
- Add your accomplishments and milestones here
#github_username: eogrady617
linkedin_username: evanjogrady
orcid_id: 0009-0007-1713-5664
formspree_email: eogrady617@gmail.com
new_formspring_endpoint: mkoyazwr
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: ''
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-algolia
- jekyll-redirect-from
paginate_path: "/projects/page:num/"
paginate: 12
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - development
